# Generated by Django 5.0.8 on 2024-08-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=300, null=True)),
                ('start_at', models.DateTimeField()),
                ('workload', models.CharField(choices=[('30', '30H'), ('45', '45H'), ('60', '60H'), ('90', '90H'), ('120', '120H')], max_length=3)),
            ],
        ),
    ]
