# Generated by Django 5.0.8 on 2024-08-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
