# Generated by Django 5.0.8 on 2024-08-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_cursos', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_at',
            field=models.DateField(),
        ),
    ]
