# Generated by Django 5.0.8 on 2024-08-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_cursos', '0003_alter_course_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
